### ISSUE TITLE
`datastores` example in README is incorrect

### ISSUE THREAD

**Issue by aereal** [k1LoW/octocov#157]
> - `local://.reports` ... `/path/to/reports` directory

from https://github.com/k1LoW/octocov/blob/767b059c1eca8c76853062211ac311b92e19a695/README.md?plain=1#L705

This example says `.reports` may be treated as the relative path from `.octocov.yml` but actually it is not.

Is it typo (`local://./reports`) ?

**Comment by k1LoW** [comment]
Oh... It's typo

**Comment by k1LoW** [comment]
Fixed https://github.com/k1LoW/octocov/commit/7129d6dfceb26f3f5a5621ddab4beace00a81e80
Thank you!!!
