### ISSUE TITLE
Environment variables required by GHES differ from error message

### ISSUE THREAD

**Issue by nowsprinting** [k1LoW/octocov#218]
### Conditions

- octocov version 0.46.0
- GHES and self hosted runner (macOS, Ubuntu)
- Set environment variables: `GH_HOST`, `GITHUB_API_URL`, `GITHUB_GRAPHQL_URL`

### push on central mode

Error occurred when Set `push` in .octocov

```
octocov version 0.46.0
Central mode enabled
Collect report of orga/repo
Collect report of orga/repo
Error: env GITHUB_TOKEN is not set
Error: Process completed with exit code 1.
```

However, what was needed was `GITHUB_ENTERPRISE_TOKEN`.

Hope to fix the message or add a note to the README.

**Comment by k1LoW** [comment]
@nowsprinting Thank you for your report!

Fixed by introducing a new version of [go-github-client](https://github.com/k1LoW/go-github-client) package.

**Comment by nowsprinting** [comment]
Thanks!
