### ISSUE TITLE
`Gh.DetectCurrentBranch` returns wrong string when current branch name contains slash

### ISSUE THREAD

**Issue by gion-pop** [k1LoW/octocov#224]
I'm using octocov from Github Actions and want to add reports to Actions Job Summaries.
I found an issue below:

`Gh.DetectCurrentBranch` parses `$GITHUB_REF` and return 3rd element of splitted slice.
https://github.com/k1LoW/octocov/blob/fb8298c5e689ccceefaaca49f42ac00e574fbeb5/gh/gh.go#L229-L231

But branch name can be contains slash. Given that branch name is `issue/123`, then `$GITHUB_REF` will be `refs/heads/issue/123`, so `Gh.DetectCurrentBranch` returns wrong branch name (`issue`), and finally `createReportContent` fail.

**Comment by k1LoW** [comment]
@gion-pop Thank you for your report!

**Comment by gion-pop** [comment]
@k1LoW I confirmed that it fixed. Thank you for quick work! 🙏
