### ISSUE TITLE
Could not detect number of pull request

### ISSUE THREAD

**Issue by FahmimRezuan** [k1LoW/octocov#227]
Here is my workflow using `workflow_run` to trigger the action. 

```
name: "Code Coverage Report"
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
     - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir -p artifacts && cd artifacts

          artifacts_url=${{ github.event.workflow_run.artifacts_url }}

          gh api --paginate "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -d "$name" "$name.zip"
          done
      - uses: k1LoW/octocov-action@v0
```

<details><summary>Build Log</summary>
<p>

Run k1LoW/octocov-action@v0
/usr/bin/docker run --name c0442a2d2e6653b5046d3b41aa510b.....
octocov version 0.47.2
Skip measuring code to test ratio: codeToTestRatio: is not set
Skip measuring test execution time: the step that was executed at the relevant time (2023-04-01 16:37:32 +0000 UTC) does not exist in the job (12448157160).
Generate coverage report badge...

            dev (61834fg)  
---------------------------
  Coverage          45.9%  

Skip commenting report to pull request: could not detect number of pull request
Adding report to job summary page...
Skip inserting report to body of pull request: body: is not set
Storing report...
Skip pushing generate files: push: is not set

</p>
</details> 

Its working when you run base on pull request. In my situation I need the test run first before we can grab the coverage report. I think it doesn't detect pull request on workflow_run. Maybe we need additional way to get the pull request if for action that triggered by workflow_run.

For me every pull request have an issue attach to it, maybe we can use this [issues api](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28) to get the pull request.

**Comment by k1LoW** [comment]
Hi @FahmimRezuan 

>  I think it doesn't detect pull request on workflow_run.

I think so too.

If there is a way to pass the pull request number externally to octocov(-action), can you pass the correct pull request number?

**Comment by FahmimRezuan** [comment]
Hi,

> If there is a way to pass the pull request number externally to octocov(-action), can you pass the correct pull request number?

Yes, we can use `${{github.event.workflow_run.pull_requests[0].number}` and pass to env. 

`- uses: k1LoW/octocov-action@v0
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.COV_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.COV_AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: "ap-southeast-1"
          DEBUG: true
          PR_NUMBER: ${{github.event.workflow_run.pull_requests[0].number}}`

**Comment by k1LoW** [comment]
I provided an environment variable `GITHUB_PULL_REQUEST_NUMBER` for receiving the pull request number.

https://github.com/k1LoW/octocov#detecting-pull-request-number

**Comment by FahmimRezuan** [comment]
> I provided an environment variable `GITHUB_PULL_REQUEST_NUMBER` for receiving the pull request number.
> 
> https://github.com/k1LoW/octocov#detecting-pull-request-number

Its working now. Thanks.
