### ISSUE TITLE
Increase format presision of Code to Test Ratio

### ISSUE THREAD

**Issue by atsushi-ishibashi** [k1LoW/octocov#230]
It takes a lot of time and effort to increase the test coverage by 10%. Sometimes it is impossible to achieve it, for example from 80% to 90% and from 90 to 100.
Why don't we use 2 or 3 decimal places as default? In my case, this change will motivate me to write test codes.
This may break changes but I think it won't change any system behaviors.

If you agree the proposal, I'll make a pull-request👍
https://github.com/k1LoW/octocov/blob/bdda036c59ac40b949f6b76f6e4f741e2606763a/report/report.go#LL111C32-L111C36

**Comment by atsushi-ishibashi** [comment]
When `Coverage` show up, my issue will be resolved👍 But in my repository, sometimes `Coverage` doesn't show.
Sorry for that I cannot share the detail because it is private repository.

**Comment by k1LoW** [comment]
> Increase format presision of Code to Test Ratio

> When Coverage show up, my issue will be resolved

Is this Issue about `Coverage`? Or is it about `Code to Test Ratio` ?

> Why don't we use 2 or 3 decimal places as default?

> But in my repository, sometimes Coverage doesn't show.

Is it a decimal point? Or is it a problem that is not displayed?

**Comment by atsushi-ishibashi** [comment]
Thank you for your reply.

the issue is about Code to Test Ratio.

>Is it a decimal point? Or is it a problem that is not displayed?

The problem is that coverage is not displayed.

This is metrics report when I created this issue.
<img width="307" alt="Screenshot 2023-06-11 at 15 44 53" src="https://github.com/k1LoW/octocov/assets/15537626/6fc0ea5d-41c0-4254-b520-870f141348f9">

The below is current report. So my issue was resolved.
<img width="351" alt="Screenshot 2023-06-11 at 15 45 17" src="https://github.com/k1LoW/octocov/assets/15537626/dda47abd-12a6-4c94-9ed3-0c282bb03686">

**Comment by k1LoW** [comment]
> The problem is that coverage is not displayed.

Perhaps octocov (or octocov-action) is not getting coverage at this time.
If you are running it through GitHub Actions, you can see that from octocov's output in the Actions log.

One way to debug is to download the coverage data when octocov fails to get coverage and run the octocov command locally.
