### ISSUE TITLE
code coverage report transition is reversed

### ISSUE THREAD

**Issue by rajyan** [k1LoW/octocov#267]
![image](https://github.com/k1LoW/octocov/assets/38206553/b5bb5581-5a85-4abc-89d0-df8cc30e3c4e)

As in the screenshot, the code coverage is reporting reversed transition.
The transition should be 81.4 => 92.0. This was broken in the recent release.

**Comment by k1LoW** [comment]
@rajyan Thank you for your report! THIS IS BUG.
