### ISSUE TITLE
Error: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by abhijit-nightfall** [k1LoW/octocov#298]
Exactly followed the setup steps as in docs but getting an error message  "Error: MissingRegion: could not find region configuration" 
How to configure region when trying to send report to Amazon S3.
<img width="854" alt="Screenshot 2023-11-02 at 7 07 52 PM" src="https://github.com/k1LoW/octocov/assets/127822984/c4b004bd-ba7f-43c6-8616-557e9ca69fdf">

**Comment by k1LoW** [comment]
Thank you for your report.

Could you set `AWS_REGION` and try it?

**Comment by abhijit-nightfall** [comment]
I had set the value of `AWS_REGION` in the repository and organization variable but continued to get the error.

**Comment by k1LoW** [comment]
Thank you for trying it. I will check it here as well.

**Comment by k1LoW** [comment]
> getting an error message "Error: MissingRegion: could not find region configuration"

Does this error occur in either repository (central or not)?

**Comment by abhijit-nightfall** [comment]
This is occurring in the private repo while storing the report. I have not tried to fetch the report from the central repo when the report can't be stored only.

**Comment by k1LoW** [comment]
Fixed in [v0.54.6](https://github.com/k1LoW/octocov/releases/tag/v0.54.6)
If you still reproduce it, please reopen.
