### ISSUE TITLE
Add an option to specify files to be excluded from coverage aggregation

### ISSUE THREAD

**Issue by furusax0621** [k1LoW/octocov#322]
Hi, thanks for the great project.

Starting with Go 1.22, the coverage report output will change for code that does not have its own tests.

https://tip.golang.org/doc/go1.22#go-command
> go test -cover now prints coverage summaries for covered packages that do not have their own test files. Prior to Go 1.22 a go test -cover run for such a package would report
> 
> ? mymod/mypack [no test files]
> 
> and now with Go 1.22, functions in the package are treated as uncovered:
> 
> mymod/mypack coverage: 0.0% of statements

For example, the report output for this project will change as follows:

```
$ go version
go version go1.22rc2 darwin/arm64

$ go test ./cmd/ -coverprofile=coverage.out
	github.com/k1LoW/octocov/cmd		coverage: 0.0% of statements

$ cat coverage.out
mode: set
github.com/k1LoW/octocov/cmd/badge.go:54.54,57.44 3 0
github.com/k1LoW/octocov/cmd/badge.go:57.44,59.4 1 0
github.com/k1LoW/octocov/cmd/badge.go:60.3,63.17 3 0
github.com/k1LoW/octocov/cmd/badge.go:63.17,65.4 1 0
github.com/k1LoW/octocov/cmd/badge.go:67.3,68.20 2 0
github.com/k1LoW/octocov/cmd/badge.go:68.20,70.18 2 0
github.com/k1LoW/octocov/cmd/badge.go:70.18,72.5 1 0
github.com/k1LoW/octocov/cmd/badge.go:73.4,73.17 1 0
...
```

Many projects will see unintended coverage drops due to this change.
However, it is difficult to mechanically distinguish between "code without intentionally written tests" and "code with poorly written tests" based on the information in the report alone.

So I want to add a new option to the `.octocov.yml` configuration file. That is, add the following `exclude` option, such as:

```yaml
coverage:
  if: true
  acceptable: current >= 60%
  exclude:
    - "github.com/k1LoW/octocov/cmd/*.go"
```

In the above example, lines matching `"github.com/k1LoW/octocov/cmd/*.go"` are excluded from coverage aggregation.

I believe this idea will make this project better. Please consider it.

Thank you.

**Comment by k1LoW** [comment]
@furusax0621 Thank you for your nice proposal!

Looks good to me!

**Comment by k1LoW** [comment]
I think this needs to be covered in every supported coverage format.

**Comment by k1LoW** [comment]
@furusax0621 Thank you! Fix it!

**Comment by furusax0621** [comment]
Thanks !!
I look forward to the next release.
