### ISSUE TITLE
Coverage calculation results have changed since v0.57.0

### ISSUE THREAD

**Issue by furusax0621** [k1LoW/octocov#325]
When using v0.57.0, gocover's coverage calculation results are lower than v0.56.x.
For example, v0.56.4 is used for test data from this repository, the coverage would be as follows:

```
~/ghq/github.com/k1LoW/octocov/coverage/testdata/gocover main
❯ octocov -v
octocov version 0.56.4

~/ghq/github.com/k1LoW/octocov/coverage/testdata/gocover main
❯ octocov -r coverage.out

            main (faa6ab0)
----------------------------
  Coverage           68.0%
```

But with v0.57.0, the coverage would be as follows:

```
~/ghq/github.com/k1LoW/octocov/coverage/testdata/gocover main
❯ octocov -v
octocov version 0.57.0

~/ghq/github.com/k1LoW/octocov/coverage/testdata/gocover main
❯ octocov -r coverage.out

            main (faa6ab0)
----------------------------
  Coverage           65.1%
```

I thin the problem is caused by the `(*Coverage).reCalc()` method being called.
https://github.com/k1LoW/octocov/blob/faa6ab086a685c2d33531f5933929b8ece7fbd47/coverage/merge.go#L25-L39

This method calculates file coverage from line coverage. However, this approach is not appropriate because the coverage representation of gocover is different from other formats.

For example, in the following block, the value of "numberOfStatements" is 1 for lines 45 through 47, so the number of rows to be recorded is 1, not 3.

https://github.com/k1LoW/octocov/blob/faa6ab086a685c2d33531f5933929b8ece7fbd47/coverage/testdata/gocover/coverage.out#L12

However, if the `(BlockCoverages).ToLineCoverages()` method is called, the line coverage for this block is counted as 3.

**Comment by furusax0621** [comment]
I think the calculation method in the reCalc method needs to be changed based on the format of the file. I have an idea for a solution, may I propose it?

**Comment by k1LoW** [comment]
@furusax0621 Thank you for your report.

> For example, in the following block, the value of "numberOfStatements" is 1 for lines 45 through 47, so the number of rows to be recorded is 1, not 3.

There are 3 types of coverage formats supported by octocov

1. TypeLOC (counting by rows)
2. TypeStmt (counts per statement)
3. TypeMerged (mixed)

If the coverage consists only of TypeStmt, like gocover, as you say, then it should be counted by TypeStmt.

> I think the calculation method in the reCalc method needs to be changed based on the format of the file. I have an idea for a solution, may I propose it?

Thank you!
