### ISSUE TITLE
Acceptable Coverage calculation is inconsistent 

### ISSUE THREAD

**Issue by abhijit-nightfall** [k1LoW/octocov#370]
**Scenario 1: Acceptable coverage correctly calculates, and the build check passes**
octocov.yml
coverage:
  acceptable: current >= 77.8%
  
![Screenshot 2024-05-23 at 12 29 45 PM](https://github.com/k1LoW/octocov/assets/127822984/939202d4-b7f8-4fcf-996b-83f82256145d)

**Scenario 2: Acceptable coverage incorrectly calculates, and the build check fails**
octocov.yml
coverage:
  acceptable: current >= 32.6%
  
![Screenshot 2024-05-23 at 12 33 21 PM](https://github.com/k1LoW/octocov/assets/127822984/906fecba-aba7-4627-8721-3896df45cc1b)

NOTE: current coverage needs to be at least 0.01% above the acceptable for the check to pass

**Comment by k1LoW** [comment]
@abhijit-nightfall Thank you for your report!

This looks like a bug.

**Comment by abhijit-nightfall** [comment]
@k1LoW Thanks for the super fast fix.
