### ISSUE TITLE
[FEATURE REQUEST] Enable use of `**`/ `*` in coverage.paths

### ISSUE THREAD

**Issue by ostk0069** [k1LoW/octocov#387]
Hi, thanks for creating great library!
I would like to send a feature request:

```octocov.yml
coverage:
  paths:
    - domain/**/lcov.info
    - domain/*/lcov.info
```
looks much nicer if it could read `domain/hoge/lcov.info` , `domain/hoge/fuga/lcov.info` for these settings for using `**` / `*` .

**Comment by k1LoW** [comment]
@ostk0069 Thank you for your resuest!
