### ISSUE TITLE
[FEATURE REQUEST] add update option when post github comment

### ISSUE THREAD

**Issue by ostk0069** [k1LoW/octocov#391]
When using [octocov action](https://github.com/k1LoW/octocov-action), this post comment.
after any push commit happens, the comment create new comment and hide or delete the current comment.
this makes a notify to user who subscribes github repository. 
Why not update the current comment text instead of creating a new one.

**Comment by k1LoW** [comment]
@ostk0069 Thank you for your request.

How about displaying it in the body of the Pull Request instead of in the comments?

https://github.com/k1LoW/octocov?tab=readme-ov-file#body

We believe that report comments should be displayed in line with the commit timeline.

**Comment by ostk0069** [comment]
@k1LoW Thanks! 

> How about displaying it in the body of the Pull Request instead of in the comments?

This looks very nice ❤️
